# Generated by Django 2.2 on 2019-07-01 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dinner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dinnerinfo',
            options={'verbose_name': '饭局信息', 'verbose_name_plural': '饭局信息'},
        ),
    ]
