# Generated by Django 2.2 on 2019-06-28 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dinner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingDinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_reason', models.CharField(max_length=100)),
                ('remark', models.CharField(max_length=100)),
                ('dinner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dinner.DinnerInfo')),
                ('sing_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sing_table',
            },
        ),
    ]
