# Generated by Django 2.2 on 2019-07-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('parent_id', models.IntegerField(verbose_name='父类id')),
                ('area_sort', models.IntegerField(verbose_name='排序')),
                ('city_type', models.IntegerField(verbose_name='类型')),
            ],
        ),
        migrations.AlterModelOptions(
            name='singdinner',
            options={'verbose_name': '饭局报名表', 'verbose_name_plural': '饭局报名表'},
        ),
    ]
